-- ============================================================
-- 0040 · Recuperar leads de Fede — insertados como sin asignar
-- Usar ON CONFLICT DO NOTHING por si alguno ya existe en la DB
-- con el mismo phone. Después asignar a Fede desde /admin/leads
-- ============================================================

INSERT INTO public.leads (first_name, last_name, phone, email, current_status, batch_id, created_at, updated_at)
VALUES
  ('Sahid',      NULL,                        '50244990907',    'sahidfarach@hotmail.com',              'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Carla',      'Ramona acosta',             '543855032838',   'porartedeamor98@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Tania',      'Itali domínguez martínez',  '5217752053669',  'italidom28@gmail.com',                 'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Yesica',     NULL,                        '5492616254454',  'yesicajsanchez@gmail.com',             'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Ayrton',     'R',                         '541136552770',   'ayrtonramos99@gmail.com',              'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Carmen',     'Anthuanett oliva espinoza', '51987590992',    'anthuanettolivaespinoza@gmail.com',    'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Sonia',      'Mariela becker',            '543764688412',   'sonia28.93.becker@gmail.com',          'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Jairo',      NULL,                        '573237335807',   'jortegat@hotmail.com',                 'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Sergio',     'Fehr',                      '5493512478385',  'sergiofehr@gmail.com',                 'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('José',       'Luis',                      '5492634367332',  'jv6369539@gmail.com',                  'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Yanela',     'Elizabeth',                 '543704782461',   'yianee.222@gmail.com',                 'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Guillermo',  NULL,                        '5492254586431',  'guillermopinamar2026@gmail.com',       'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Iraisy',     'Machado gragirena',         '14073009227',    'iraisym@gmail.com',                    'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Genaro',     'Emil',                      '542604021082',   'cortezgenaro682@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Santiago',   'Navarro',                   '5491125222055',  'santiago.navarro2019@gmail.com',       'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Micaela',    NULL,                        '5491133225452',  'micaelaymilo1996@gmail.com',           'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Luna',       'Coronel',                   '541127387170',   'lunacoronel333@gmail.com',             'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Wanda',      'Tamara becerra',            '5492664773904',  'wandatamarabecerra98@gmail.com',       'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Samuel',     'Gonzalez mackeldey',        '573016565588',   'sdgmackeldey@gmail.com',               'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Melanie',    NULL,                        '5491150125729',  'melysabrina53@gmail.com',              'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Beatriz',    'Choy',                      '50767972259',    'beatrizchoy31@hotmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Bruno',      NULL,                        '5493794520437',  'brunolopezcuajo@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Keily',      'Milla',                     '12142644770',    'keilygaleano07@gmail.com',             'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Santiago',   NULL,                        '5491168897975',  'santiago.m.anfuso@gmail.com',          'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Juan',       'Sebastian vilbao tibaduiza','1573054167082',  'juan.vilbao2011@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Julián',     'Paladines',                 '593987115301',   'paladinesjulian7108@gmail.com',        'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Agustin',    NULL,                        '5493512957068',  'penzomaximiliano2000@gmail.com',       'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Carla',      NULL,                        '5493413929563',  'blandocarla@gmail.com',                'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Denys',      'Pantoja rubio',             '5713106533504',  'denyspantoja389@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Fiorela',    NULL,                        '5492213043512',  'fiorecasas88@gmail.com',               'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Mariangel',  'Espinosa',                  '573234369080',   'mariangele38@gmail.com',               'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Carola',     NULL,                        '5493425971715',  'carolamorra1980@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Ayelen',     NULL,                        '5493888688728',  'aye.smt0910@gmail.com',                'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Azael',      'Bernal',                    '50766267303',    'azael.bernal04@gmail.com',             'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Alicia',     NULL,                        '5493883631111',  'alicia.ponce.272727@gmail.com',        'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Sofia',      'Teran',                     '542617219951',   'sofi.teran.02@gmail.com',              'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Jose',       'Danilo ortiz',              '543873622861',   'juancithogilyup243@gmail.com',         'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Ariel',      NULL,                        '5491123994313',  'canterokevin640@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Alex',       'Gilberto leguizamo mendoza','573232385918',   'jalexdavid749@gmail.com',              'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Selena',     NULL,                        '5491156210974',  'villalbaselena23@gmail.com',           'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Rocio',      'Celeste chamorro',          '5491135994543',  'chamorrorocio01@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Romina',     'Mañas',                     '5492235930977',  'manasromina5@gmail.com',               'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Luis',       'Gonzalez',                  '5215549664371',  'lsgo2906@gmail.com',                   'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Ariel',      'Barrios benitez',           '595983041910',   'arielbarriosbenitez5@gmail.com',       'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Natalia',    NULL,                        '5493855902147',  'ferzuanael@gmail.com',                 'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Eliza',      'Sant',                      '34654300547',    'liza_sant@hotmail.es',                 'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Brian',      'Bayarri',                   '542616405767',   'bayarribrian799@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Cintia',     'Belen baiz',                '543425912267',   'cinbelbaiz@gmail.com',                 'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Jonathan',   'Gómez romero',              '5219642252796',  'barbie270698@icloud.com',              'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Oscar',      'Jesús salas',               '56949911144',    'salasoscar022@gmail.com',              'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Diego',      'Escobar',                   '50376358616',    'diefer13@yahoo.com',                   'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Mirian',     'Visentin',                  '543416146714',   'noemivstn@gmail.com',                  'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Vins',       'Santillán reyes',           '524499900972',   'alexreyes3465@gmail.com',              'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Daniela',    'Daniela retamal',           '5492994623883',  'dretamal@hotmail.com.ar',              'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Gerardo',    'Gomez',                     '541133143194',   'amoelmarsiempre@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Florencia',  'Meana',                     '542478541605',   'meanafloor1@gmail.com',                'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Leone',      NULL,                        '5491133117479',  'leo-kpo10@hotmail.com',                'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Agustina',   'Silvero',                   '541168296243',   'agustinanoeli30@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Facundo',    'Scheble',                   '5493547319013',  'facundoscheble006@gmail.com',          'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Vane',       'Sarrio',                    '5492214590559',  'sarriovane@gmail.com',                 'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Richar',     'Ricardo mamani',            '5493813219054',  'richarmamani454@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Luisa',      'Maria polo lasso',          '573044422779',   'luisalasso402@gmail.com',              'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Matías',     'Aaron mónaco',              '542617481452',   'matiasaaron172008@gmail.com',          'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Miguel',     'Jara',                      '56963995664',    'jara.miguelangel.23@gmail.com',        'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Graciela',   'Cuenca',                    '543772629008',   'gracielaitaticuenca3@gmail.com',       'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Juan',       'Bollatti',                  '543534099602',   'marcelobollatti926@gmail.com',         'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Rodney',     NULL,                        '595981571595',   'rodneyramirez881@gmail.com',           'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Roco',       'Jaquelina leguizamón',      '543735310238',   'rociojaqueline97@gmail.com',          'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Jesica',     'Mariel chocobar',           '543875997384',   'jesicamarielchocobar@gmail.com',       'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Analía',     NULL,                        '5491158211739',  'romeroanaliam@gmail.com',              'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Candela',    NULL,                        '5491164097580',  'candecarballo68@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Agustin',    NULL,                        '5493364579667',  'agustinlescano1927@gmail.com',         'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Santiago',   'Barboza',                   '543416828822',   'saanti.barboza14@gmail.com',           'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Elizabeth',  'Wavrenchuk',                '541163606414',   'beth.wavrenchuk33333@gmail.com',       'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Isabelle',   NULL,                        '34613866018',    'camila250500@gmail.com',               'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Tamara',     NULL,                        '5522996140917',  'tami.saavedra.1@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Adrián',     NULL,                        '541126666918',   'fnestor332@gimail.xn--cmo-gna',        'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Analia',     NULL,                        '5491136599910',  'analiaelisabetha@gmail.com',           'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Karina',     'Dávila',                    '59178079428',    'karinardavila76@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Paola',      'Britez',                    '543751404684',   '442270070pab@gmail.com',               'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Gisela',     'Cecilia mamondez',          '543572686499',   'cecigallardo2406@gmail.com',           'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Yesica',     'Ochi',                      '542634845737',   'yesiochi78@gmail.com',                 'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Yanina',     NULL,                        '5492323618610',  'asesora.musso@gmail.com',              'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Julieta',    NULL,                        '34633551523',    'mjbagnasco@hotmail.com',               'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Marcelo',    NULL,                        '5493755237784',  'mv3647662@gmail.com',                  'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('German',     'Leonel montero',            '542966750920',   'germanleonel001@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Brian',      'Nahuel leyes reta',         '542617059042',   'leyesnahuel12@gmail.com',              'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Cris',       'Acuña',                     '5492916480905',  'acunacristel847@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Agustín',    'Torres',                    '541125792443',   'agustorres0713@gmail.com',             'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Sergio',     'Sergio curieses',           '5492324691808',  'valelucaser1@yahoo.it',                'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Sebastian',  'Yassin cárdenas muñoz',     '573188105222',   'sebastianyassin4434@gmail.com',        'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Anabella',   'Bustos',                    '5493406437201',  'bustosanabella142@gmail.com',          'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Ezequiel',   'Andres morales',            '5492944712050',  'em884222@gmail.com',                   'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Isaac',      'Daniel macedo saavedra',    '51928435077',    'daniel160924@gmail.com',               'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Edgardo',    NULL,                        '5492964560371',  'juanedgardoquiroga9@gmail.comj',       'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Sergio',     'Imanol ibañez',             '5493875818773',  'imanolsandoval8@gmail.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Pepe',       NULL,                        '593987794335',   'info.artecla@gmail.com',               'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Grace',      'Diaz peralta',              '573105005053',   'gracediaz0508@outlook.com',            'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Santiago',   'Cignio',                    '542224534740',   'santiagocignio307@gmail.com',          'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now()),
  ('Adriana',    NULL,                        '5493512425633',  'adru_zing@hotmail.com',                'NO_CONTACTADO', 'recuperacion-fede-28jun', now(), now())
ON CONFLICT DO NOTHING;

-- Verificar cuántos se insertaron:
SELECT count(*) as insertados FROM public.leads WHERE batch_id = 'recuperacion-fede-28jun';
